# Generated by CMake, DO NOT EDIT
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/CMakeFiles/cmake.check_cache: \
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/CMakeFiles/2.8.11.2/CMakeCCompiler.cmake\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/CMakeFiles/2.8.11.2/CMakeSystem.cmake\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/CMakeLists.txt\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/cmake/Modules/FindLibUSB.cmake\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/cmake/Modules/FindThreads.cmake\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/cmake/cmake_uninstall.cmake.in\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/include/CMakeLists.txt\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/librtlsdr.pc.in\
/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni/src/CMakeLists.txt\
/opt/local/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeConfigurableFile.in\
/opt/local/share/cmake-2.8/Modules/CMakeFindXCode.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CheckFunctionExists.c\
/opt/local/share/cmake-2.8/Modules/CheckIncludeFiles.cmake\
/opt/local/share/cmake-2.8/Modules/CheckLibraryExists.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/Clang-C.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/Clang.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/opt/local/share/cmake-2.8/Modules/FindPkgConfig.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-Clang-C.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-Clang.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/UnixPaths.cmake
	/opt/local/bin/cmake -H/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni -B/Users/sciencectn/Documents/CURRENT_Lab/android-rtlsdr-as/app/jni
